# Generated by Django 2.2.28 on 2023-04-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_newmo_value2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wolf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wolf_enemy', to='home.Alligator')),
            ],
        ),
    ]
